name: DevOps Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: lucabaserga/node-web-app:${{github.sha}}

  azure-deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: docker-build-and-push

    steps:
      - name: Deploy to Azure Web App 
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'lucabaserga/node-web-app:${{github.sha}}'
